### ISSUE TITLE
Create a sitemap

### ISSUE THREAD

**Issue by pheeria** [Lernwerkstatt/site#173]
- [x] Create a sitemap
- [x] Add to robots.txt
- [x] Submit to Google Search Console

**Comment by pheeria** [comment]
#166

**Comment by pheeria** [comment]
Unfortunately, `sitemap.xml` is not accessible on our website with 'Not Found' and `robots.txt` doesn't include `Sitemap` value.
Everything is fine in the codebase.
Any ideas @cappyccino @jarjan @starmaerker @hikes101?

**Comment by pheeria** [comment]
I submitted the site Google Search Console, they've requested a DNS entry, which I did. Then I wanted to reference the sitemap, and this is how I found that it doesn't show up on the website.

**Comment by hikes101** [comment]
Did we try merging anything else with master in the last days to see if the changes go online?

**Comment by pheeria** [comment]
Not yet, I guess we will try with your noopener PR

**Comment by hikes101** [comment]
I just merged the noopener PR but the [online version](https://www.die-lernwerkstatt.org/) doesn't show any changes. Should it be updated right away when there is a change on master? In this case something doesn't work correctly...

**Comment by starmaerker** [comment]
There was a failure in Azure. I redeployed the last PR. The sitemap.xml is now showing up.

**Comment by pheeria** [comment]
Thank you very much! I just submitted to the sitemap to Google Search Console.
