### ISSUE TITLE
Submit URL to Bing

### ISSUE THREAD

**Issue by pheeria** [Lernwerkstatt/site#174]
[Only hardcore, only XML](https://www.bing.com/webmaster/help/submit-urls-to-bing-62f2860a) :)

Please, attach a submission screenshot.

**Comment by hikes101** [comment]
I submitted the sitemap but the xml file is still unavailable.

![image](https://user-images.githubusercontent.com/34481945/66740366-481caf80-ee73-11e9-8e2f-17ee41103476.png)
