### ISSUE TITLE
Update mongoose

### ISSUE THREAD

**Issue by pheeria** [Lernwerkstatt/site#186]
Vulnerability alert [from here](https://github.com/Lernwerkstatt/site/network/alert/package-lock.json/mongoose/open)

**Comment by hikes101** [comment]
@pheeria I get a 404 when clicking on the link...

**Comment by pheeria** [comment]
@hikes101 , sorry, here is the screenshot:

![image](https://user-images.githubusercontent.com/15848876/67579202-4771fc00-f744-11e9-83c7-134a52d614ff.png)
