### ISSUE TITLE
Default locale

### ISSUE THREAD

**Issue by pheeria** [Lernwerkstatt/site#195]
Currently, default locale is properly set to `de`, but the texts are still shown in English.

**Comment by hikes101** [comment]
@pheeria I guess it's the same issue as [described here](https://stackoverflow.com/questions/28479990/express-and-i18n-default-locale-not-working). Cookies and `accept-language` are checked first. Should work if your accept-language is German.

**Comment by danielstreif** [comment]
@starmaerker is your default language German? If yes, could you test what default language is shown to you? Thanks!

**Comment by danielstreif** [comment]
@pheeria do you want to keep this issue or close it?
