### ISSUE TITLE
Privacy notice

### ISSUE THREAD

**Issue by pheeria** [Lernwerkstatt/site#196]
We need a privacy notice (Urheberrecht und der Datenschutzerklärung), like on the Contact page, to be also present for a Subscribe page.
Furthermore, on the Support page, we also need a reference to the policies, as a bullet point number 4. 

4. "Hier findest du unsere Datenschutzerklärung, mit weiteren Informationen zum Umgang mit deinen Daten."

**Comment by jarjan** [comment]
@hikes101 @pheeria yes, since now this form is not working, we should create a new one in mailchimp account of lernwerkstatt
