### ISSUE TITLE
humans.txt

### ISSUE THREAD

**Issue by pheeria** [Lernwerkstatt/site#197]
Include our names/emails to humans.txt

**Comment by hikes101** [comment]
@pheeria a list with all our names and email addresses or should we just use the dev@die-lernwerkstatt.org address? In case we want all email addresses I need a list with the address everyone wants to use

**Comment by pheeria** [comment]
This is opt-in, so everyone should decide. 
Mine is olzhas.askar@gmail.com 😉

**Comment by hikes101** [comment]
Alright, @jarjan @starmaerker let me know if you want your email and name on there

**Comment by jarjan** [comment]
zharzhan@gmail.com is mine :)
