### ISSUE TITLE
Downloadable files

### ISSUE THREAD

**Issue by hikes101** [Lernwerkstatt/site#202]
Problem description:
The download links for the pdf documents "Satzung" and "Mitgliedsantrag" lead to strikingly. Right now they still work but we should move the files to another location to be independent of strikingly.

Suggested solution:
Upload the files on MongoDB or another location and change the link paths accordingly.

**Comment by pheeria** [comment]
Let's move them to `data` or `static` directory?
As far as I know MongoDB is a json based database, it would be not very handy to serialize/deserialize the file to binary.

**Comment by jarjan** [comment]
We can put in inside static in some folder, make a link with `download` attribute, this way browser will download it.
Here is more: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download

**Comment by pheeria** [comment]
This is a really good catch, @hikes101!
Thank you for being attentive! 🎉
