### ISSUE TITLE
Renew SSL Certificate

### ISSUE THREAD

**Issue by pheeria** [Lernwerkstatt/site#230]
Expires on 4th of January

![image](https://user-images.githubusercontent.com/15848876/71659366-a311c480-2d47-11ea-8f30-0ecc35752fb5.png)

**Comment by danielstreif** [comment]
@pheeria Do we have some kind of documentation for this? Then I could try it. Don't really know what you did there when you set it up.

**Comment by pheeria** [comment]
@danielstreif I'll take care of that. But there is a documentation in our Wiki :)
