### ISSUE TITLE
Fix Prettier legacy options warning

### ISSUE THREAD

**Issue by pheeria** [Lernwerkstatt/site#236]
[More here](https://www.reddit.com/r/vscode/comments/dvdhqh/legacy_options_in_prettier_config_error/)

**Comment by danielstreif** [comment]
@pheeria @jarjan the warning is created by these deprecated settings in `settings.json` as far as I understand
```
"prettier.eslintIntegration": true,
"prettier.stylelintIntegration": true
```
https://github.com/prettier/prettier-vscode#linter-integration

Do we actually need these settings? As far as I see it we are using eslint and stylelint anyway.
