### ISSUE TITLE
Enable `gzip` compression on server

### ISSUE THREAD

**Issue by jarjan** [Lernwerkstatt/site#241]
Problem description:

Right now our server doesn't compress static files. Enabling `gzip` will reduce website size which is good for mobile devices.
 
Suggested solution:

Enable `gzip` compression either in express or on server level.

**Comment by pheeria** [comment]
This is a really good suggestion! Unfortunately I couldn't find any options in Azure.
Although, there is a paid option, I guess. @starmaerker can you please elaborate?
