### ISSUE TITLE
Fix Contact form

### ISSUE THREAD

**Issue by pheeria** [Lernwerkstatt/site#267]
Our contact form seems to do nothing.

https://die-lernwerkstatt.org/contact

https://github.com/Lernwerkstatt/site/blob/master/src/views/contact.hbs

**Comment by pheeria** [comment]
How can we deal with that?
The first idea that comes to my mind is to write a mailer on the backend and accept a POST request.

**Comment by danielstreif** [comment]
Oh, how did we miss that? So as far as I see this there is just nothing happening with a submitted email? [`nodemailer`](https://nodemailer.com/about/) seems to be quite easy to use in combination with a POST request.

**Comment by pheeria** [comment]
@jarjan @danielstreif so, `nodemailer`?

**Comment by danielstreif** [comment]
@pheeria working on it

**Comment by jarjan** [comment]
One concern is that letters send through `nodemailer` could end up in spam.
